---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-setup-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    setup.template.enabled: false
    setup.ilm.enabled: false
    ilm.enabled: false
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/*.log
    output.kafka:
      enabled: true
      hosts: ${KAFKA_HOSTS}
      topic: 'gcp.file.raw'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000
---
# Run filebeat setup
apiVersion: batch/v1
kind: Job
metadata:
  name: filebeat-setup
  namespace: kube-system
spec:
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: filebeat-setup
          image: docker.elastic.co/beats/filebeat:7.2.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
            #          "setup",
          ]
          env:
            - name: KAFKA_HOSTS
              valueFrom:
                secretKeyRef:
                  name: kafka-host
                  key: kafka-hosts-ports
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: dockersock
              mountPath: /var/run/docker.sock
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: config
          configMap:
            defaultMode: 0600
            name: filebeat-setup-config
---
